import Layout from "../components/Layout";
import Head from 'next/head'
import { useState } from "react";

import { EntryScreen } from "../components/Sections/EntryScreen";
import { HeroSection } from "../components/Sections/HeroSection";
import Domains from '../components/Sections/domains'
import Footer from '../components/Sections/footer'
import Founders from '../components/Sections/founders'
import Hero from '../components/Sections/hero'
import Process from '../components/Sections/process'
import Services from '../components/Sections/Services'
import Signup from '../components/Sections/signup'
import Testimonials from '../components/Sections/testimonials'
import Work from '../components/Sections/work'
import Navbar from "../components/UX-Components/Navbar";
import { Stars } from "../components/UX-Components/Stars";

export default function Home() {

  const [loaderButtonClicked, setLoaderButtonCLicked] = useState(false)

  return (
    <Layout>
       <Head>
        <title>360space - 3D Rendering Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>
      </Head>

      {loaderButtonClicked == false ? <EntryScreen setLoaderButtonCLicked={setLoaderButtonCLicked} /> : 
       <div>
         <Navbar />
          <Hero />
          <section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
        <div class="inline-flex justify-between items-center py-1 px-1 pr-4 mb-7 text-sm text-gray-700 bg-gray-100 rounded-full dark:bg-gray-800 dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700" role="alert">
            <span class="top-0 left-7 mr-2 ml-2 w-3.5 h-3.5 bg-purple-400 border-2 border-white dark:border-gray-800 rounded-full"></span>
            <span class="text-sm font-medium">WHY CHOSE US</span> 
        </div>
        <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">We Deliver The Highest Quality</h1>
        <p class="mb-8 text-md font-normal text-gray-500 lg:text-md sm:px-16 xl:px-30 dark:text-gray-400">360Space brings the future to reality inspired by your ideas and designs through VR visualizations. It’s all done with the beating technology and precision of 360Space creative experts who are professional masters in this field. For the clients, who are architects, interior designers or real estate developers, we create IT’S-SO-REAL VR shows of 2D/3D images, videos, VR walkthroughs, and many more visual illustrations. At 360 Space Studio, we have a dedicated team of professionals, giving you the best 3D architectural visualization services. We create interactive, modern, eye-catchy renders which will help you by creating professional 3D renders that fit perfectly with your vision, needs and target audience, which will, in turn, strengthen your marketing presence.</p>
        
        <div class="px-4 mx-auto">
          <div class="bg-white">
            <div class="mx-auto grid max-w-2xl grid-cols-1 items-center gap-y-16 gap-x-8 py-24 px-4 lg:max-w-7xl lg:grid-cols-2">
              <div>
              <div class="p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800 line leading-loose" id="about" role="tabpanel" aria-labelledby="about-tab">
                  <ul role="list" class="space-y-4 text-gray-500 dark:text-gray-400">
                    <li class="flex space-x-2">
                        <svg class="flex-shrink-0 w-4 h-4 text-blue-600 dark:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        <span class="font-light leading-tight">Dynamic reports and dashboards</span>
                    </li>
                    <li class="flex space-x-2">
                        <svg class="flex-shrink-0 w-4 h-4 text-blue-600 dark:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        <span class="font-light leading-tight">Templates for everyone</span>
                    </li>
                    <li class="flex space-x-2">
                        <svg class="flex-shrink-0 w-4 h-4 text-blue-600 dark:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        <span class="font-light leading-tight">Development workflow</span>
                    </li>
                    <li class="flex space-x-2">
                        <svg class="flex-shrink-0 w-4 h-4 text-blue-600 dark:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
                        <span class="font-light leading-tight">Limitless business automation</span>
                    </li>
                  </ul>
              </div>
              </div>
              <div class="grid">
                <img src="/animated_medium_exclusivity.gif" alt="Walnut card tray with white powder coated steel divider and 3 punchout holes." class="rounded-lg bg-gray-100" />
              </div>
            </div>
          </div>

        </div> 
    </div>
</section>

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Process />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Testimonials />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Domains />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Signup />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Founders />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Services />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Work />

        <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700"></hr>

        <Footer />

       </div>
      }
    </Layout>
  );
}
